# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

pr:
- master
- 202???
- 201???

trigger:
  batch: true
  branches:
    include:
    - master
    - 202???
    - 201???

# this part need to be set in UI
schedules:
- cron: "0 0 * * 6"
  displayName: Weekly build
  branches:
    include:
    - master
    - 202???
    - 201???
  always: true

variables:
  - name: BUILD_BRANCH
    ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
      value: $(System.PullRequest.TargetBranch)
    ${{ else }}:
      value: $(Build.SourceBranchName)

stages:
- stage: Build

  jobs:
  - template: .azure-pipelines/build-template.yml
    parameters:
      arch: amd64
      sonic_slave: sonic-slave-buster
      buildimage_artifact_name: sonic-buildimage.vs
      buildimage_pipeline: 142
      swss_common_artifact_name: sonic-swss-common
      sairedis_artifact_name: sonic-sairedis
      artifact_name: sonic-swss
      archive_pytests: true
      archive_gcov: true

- stage: BuildArm
  dependsOn: Build
  condition: succeeded('Build')
  jobs:
  - template: .azure-pipelines/build-template.yml
    parameters:
      arch: armhf
      timeout: 240
      pool: sonicbld-armhf
      sonic_slave: sonic-slave-buster-armhf
      buildimage_artifact_name: sonic-buildimage.marvell-armhf
      buildimage_pipeline: 141
      swss_common_artifact_name: sonic-swss-common.armhf
      sairedis_artifact_name: sonic-sairedis.armhf
      artifact_name: sonic-swss.armhf
      archive_gcov: false

  - template: .azure-pipelines/build-template.yml
    parameters:
      arch: arm64
      timeout: 240
      pool: sonicbld-arm64
      sonic_slave: sonic-slave-buster-arm64
      swss_common_artifact_name: sonic-swss-common.arm64
      buildimage_artifact_name: sonic-buildimage.centec-arm64
      buildimage_pipeline: 140
      sairedis_artifact_name: sonic-sairedis.arm64
      artifact_name: sonic-swss.arm64
      archive_gcov: false

- stage: BuildDocker
  dependsOn: Build
  condition: succeeded('Build')
  jobs:
  - template: .azure-pipelines/build-docker-sonic-vs-template.yml
    parameters:
      swss_common_artifact_name: sonic-swss-common
      sairedis_artifact_name: sonic-sairedis
      swss_artifact_name: sonic-swss
      artifact_name: docker-sonic-vs

- stage: Test
  dependsOn: BuildDocker
  condition: succeeded('BuildDocker')
  jobs:
  - template: .azure-pipelines/test-docker-sonic-vs-template.yml
    parameters:
      log_artifact_name: log
      gcov_artifact_name: sonic-gcov
      sonic_slave: sonic-slave-buster
      archive_gcov: true

- stage: Gcov
  dependsOn: Test
  condition: always()
  jobs:
  - template: .azure-pipelines/gcov.yml
    parameters:
      arch: amd64
      sonic_slave: sonic-slave-buster
      swss_common_artifact_name: sonic-swss-common
      sairedis_artifact_name: sonic-sairedis
      swss_artifact_name: sonic-swss
      artifact_name: sonic-gcov
      archive_gcov: true
