parameters:
- name: arch
  type: string
  values:
  - amd64
  - armhf
  - arm64
  default: amd64

- name: pool
  type: string
  values:
  - sonicbld
  - sonicbld-armhf
  - sonicbld-arm64
  - default
  default: default

- name: timeout
  type: number
  default: 60

- name: sonic_slave
  type: string

- name: buildimage_artifact_name
  type: string

- name: buildimage_pipeline
  type: number

- name: sairedis_artifact_name
  type: string

- name: swss_common_artifact_name
  type: string

- name: artifact_name
  type: string

- name: archive_pytests
  type: boolean
  default: false

- name: archive_gcov
  type: boolean
  default: false

jobs:
- job:
  displayName: ${{ parameters.arch }}
  timeoutInMinutes: ${{ parameters.timeout }}

  pool:
    ${{ if ne(parameters.pool, 'default') }}:
      name: ${{ parameters.pool }}
    ${{ if eq(parameters.pool, 'default') }}:
      vmImage: 'ubuntu-20.04'

  container:
    image: sonicdev-microsoft.azurecr.io:443/${{ parameters.sonic_slave }}:latest

  steps:
  - checkout: self
    clean: true
    submodules: true
  - script: |
      sudo apt-get install -y libhiredis0.14 libhiredis-dev
      sudo apt-get install -y libzmq5 libzmq3-dev
      sudo apt-get install -qq -y \
          libhiredis-dev \
          swig3.0
      sudo apt-get install -y libdbus-1-3
      sudo apt-get install -y libteam-dev \
          libteam5 \
          libteamdctl0
    displayName: "Install dependencies"
  - task: DownloadPipelineArtifact@2
    inputs:
      source: specific
      project: build
      pipeline: 9
      artifact: ${{ parameters.swss_common_artifact_name }}
      runVersion: 'latestFromBranch'
      runBranch: 'refs/heads/master'
      path: '$(Build.SourcesDirectory)/${{ parameters.swss_common_artifact_name }}'
    displayName: "Download sonic swss common deb packages"
  - task: DownloadPipelineArtifact@2
    inputs:
      source: specific
      project: build
      pipeline: 12
      artifact: ${{ parameters.sairedis_artifact_name }}
      runVersion: 'latestFromBranch'
      runBranch: 'refs/heads/master'
      path: '$(Build.SourcesDirectory)/${{ parameters.sairedis_artifact_name }}'
    displayName: "Download sonic sairedis deb packages"
  - task: DownloadPipelineArtifact@2
    ${{ if eq(parameters.buildimage_pipeline, 141) }}:
      continueOnError: True
    inputs:
      source: specific
      project: build
      pipeline: ${{ parameters.buildimage_pipeline }}
      artifact: ${{ parameters.buildimage_artifact_name }}
      runVersion: 'latestFromBranch'
      runBranch: 'refs/heads/master'
      path: '$(Build.SourcesDirectory)/${{ parameters.buildimage_artifact_name }}'
    displayName: "Download sonic buildimage deb packages"
  - script: |
      buildimage_artifact_downloaded=n
      [ -d "$(Build.SourcesDirectory)/${{ parameters.buildimage_artifact_name }}/target" ] && buildimage_artifact_downloaded=y
      echo "buildimage_artifact_downloaded=$buildimage_artifact_downloaded"
      echo "##vso[task.setvariable variable=buildimage_artifact_downloaded]$buildimage_artifact_downloaded"
    condition: eq(${{ parameters.buildimage_pipeline }}, 141)
    displayName: "Check if sonic buildimage deb packages downloaded"
  - task: DownloadPipelineArtifact@2
    condition: and(eq(variables.buildimage_artifact_downloaded, 'n'), eq(${{ parameters.buildimage_pipeline }}, 141))
    inputs:
      source: specific
      project: build
      pipeline: ${{ parameters.buildimage_pipeline }}
      artifact: 'sonic-buildimage.marvell-armhf1'
      runVersion: specific
      runId: 80637
      path: '$(Build.SourcesDirectory)/${{ parameters.buildimage_artifact_name }}'
    displayName: "Download sonic buildimage deb packages from 80637"
  - script: |
      cd $(Build.SourcesDirectory)/${{ parameters.buildimage_artifact_name }}
      sudo dpkg -i target/debs/buster/libnl-3-200_*.deb
      sudo dpkg -i target/debs/buster/libnl-3-dev_*.deb
      sudo dpkg -i target/debs/buster/libnl-genl-3-200_*.deb
      sudo dpkg -i target/debs/buster/libnl-genl-3-dev_*.deb
      sudo dpkg -i target/debs/buster/libnl-route-3-200_*.deb
      sudo dpkg -i target/debs/buster/libnl-route-3-dev_*.deb
      sudo dpkg -i target/debs/buster/libnl-nf-3-200_*.deb
      sudo dpkg -i target/debs/buster/libnl-nf-3-dev_*.deb
      cd $(Build.SourcesDirectory)/${{ parameters.swss_common_artifact_name }}
      sudo dpkg -i libswsscommon_1.0.0_${{ parameters.arch }}.deb
      sudo dpkg -i libswsscommon-dev_1.0.0_${{ parameters.arch }}.deb
      cd $(Build.SourcesDirectory)/${{ parameters.sairedis_artifact_name }}
      sudo dpkg -i libsaivs_*.deb
      sudo dpkg -i libsaivs-dev_*.deb
      sudo dpkg -i libsairedis_*.deb
      sudo dpkg -i libsairedis-dev_*.deb
      sudo dpkg -i libsaimetadata_*.deb
      sudo dpkg -i libsaimetadata-dev_*.deb
      sudo dpkg -i syncd-vs_*.deb
    workingDirectory: $(Pipeline.Workspace)
    displayName: "Install libnl3, sonic swss common and sairedis"
  - script: |
      set -x
      tar czf pytest.tgz tests
      cp -r pytest.tgz $(Build.ArtifactStagingDirectory)/
      if [ '${{ parameters.archive_gcov }}' == True ]; then
         export ENABLE_GCOV=y
      fi
      ./autogen.sh
      dpkg-buildpackage -us -uc -b -j$(nproc) && cp ../*.deb .
    displayName: "Compile sonic swss"
  - publish: $(System.DefaultWorkingDirectory)/
    artifact: ${{ parameters.artifact_name }}
    displayName: "Archive swss debian packages"
  - publish: $(Build.ArtifactStagingDirectory)/
    artifact: sonic-swss-pytests
    displayName: "Archive swss pytests"
    condition: eq('${{ parameters.archive_pytests }}', true)
